"""What `--autogenerate` is allowed to notice (D-332).

Lives here rather than inside `alembic/env.py` so it can be imported and tested. `env.py` is loaded
by Alembic from a path, not as a package module, so a predicate defined there is only exercisable
by running a real migration against a real database - which is exactly the check you want to be
cheap.
"""

# Tables Postgres owns that `Base.metadata` deliberately does not describe.
#
# LangGraph's `AsyncPostgresSaver` creates and migrates these four itself at application start.
# They hold every live learning and chat session, and they are invisible to SQLAlchemy - so
# autogenerate reads "present in the database, absent from the models" as "should be dropped" and
# emits `op.drop_table` for all four.
#
# This was not hypothetical. The autogenerated draft of `6538a95bc990_d331_learning_sessions`
# contained drops for all four against a database holding 1,275,766 checkpoint rows. It was caught
# by reading the draft; this filter is here so that reading it is a backstop, not the only defence.
UNMANAGED_TABLES = frozenset(
    {
        "checkpoints",
        "checkpoint_writes",
        "checkpoint_blobs",
        "checkpoint_migrations",
    }
)


def include_object(
    obj: object, name: str | None, type_: str, reflected: bool, compare_to: object
) -> bool:
    """Keep autogenerate's hands off tables this project does not declare.

    Scoped to `reflected` objects only: a table *in the models* named `checkpoints` would still be
    generated normally. This suppresses "the database has something my metadata does not", which is
    the only direction that produces a destructive diff.

    **Does not cover the other half of the same trap.** Indexes created by earlier migrations
    rather than declared on a model (`ix_rag_chunks_embedding_hnsw` and three siblings) are also
    proposed for dropping. Those are index-level, non-destructive to row data, and filtering them
    by name would silently mask a genuine index removal - so they stay a read-the-draft
    responsibility. **Always read a generated migration before running it.**
    """
    if type_ == "table" and reflected and name in UNMANAGED_TABLES:
        return False
    return True
