"""learning session and study items

Revision ID: 05a193bc739b
Revises: 9e6877432c14
Create Date: 2026-07-15 17:16:12.952487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a193bc739b'
down_revision: Union[str, Sequence[str], None] = '9e6877432c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('learning_session_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=True),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('week_id', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('pre_assessment_session_id', sa.String(), nullable=True),
    sa.Column('study_session_id', sa.String(), nullable=True),
    sa.Column('post_assessment_session_id', sa.String(), nullable=True),
    sa.Column('blocked_session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_session_id'], ['blocked_sessions.blocked_session_id'], ),
    sa.ForeignKeyConstraint(['post_assessment_session_id'], ['assessment_sessions.assessment_session_id'], ),
    sa.ForeignKeyConstraint(['pre_assessment_session_id'], ['assessment_sessions.assessment_session_id'], ),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.study_session_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('learning_session_id')
    )
    op.create_index(op.f('ix_learning_sessions_student_external_id'), 'learning_sessions', ['student_external_id'], unique=False)
    op.create_table('study_items',
    sa.Column('study_item_id', sa.String(), nullable=False),
    sa.Column('study_session_id', sa.String(), nullable=False),
    sa.Column('question_variant_id', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_variant_id'], ['question_variants.question_variant_id'], ),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.study_session_id'], ),
    sa.PrimaryKeyConstraint('study_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_items')
    op.drop_index(op.f('ix_learning_sessions_student_external_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
