"""d333_memory_consolidated_at - the gate the retention job checks before deleting

Revision ID: 4cfc45b7c5ff
Revises: 6538a95bc990
Create Date: 2026-08-15

The user's rule (D-333): *run long-term memory consolidation first; only delete the checkpoint
after consolidation succeeds, and retain/retry it if consolidation fails.*

This column is what makes "succeeds" checkable per session, and what keeps the rule from being a
cost bug. `consolidate_student_session` is a **paid Bedrock call** and it already runs at
`finalize_exam`, so a job that re-consolidated every eligible thread would re-pay for work already
done, at a volume that scales with the backlog. Nullable with no backfill: a session consolidated
before this column existed is recognised by evidence rather than by a default that would assert
something the database cannot support.

Hand-written rather than autogenerated - see `6538a95bc990`'s docstring and D-332 for why every
migration in this project is now read before it is run.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4cfc45b7c5ff"
down_revision: str | Sequence[str] | None = "6538a95bc990"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "learning_sessions",
        sa.Column("memory_consolidated_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("learning_sessions", "memory_consolidated_at")
