"""authored question bank fields and validation runs

Revision ID: 529d2f1df0af
Revises: 6af7c901bab1
Create Date: 2026-07-19 12:52:08.102903

S20 (SPEC §5.8.2-5.8.5, plan §7): adds the authored-item column group to
`question_templates` (nullable/defaulted so existing "shape" rows are unaffected) plus
the new `question_validation_runs` audit table. `server_default` is supplied on the two
new NOT NULL columns so this applies to a DB that already holds template rows and still
replays cleanly from an empty schema (matches `f6dcf62cdba4`'s convention) - the
application always sets these columns explicitly, the defaults are migration-safety
only. The autogenerated diff also proposed dropping the LangGraph `checkpoint*` tables
(created at runtime by `AsyncPostgresSaver`, not by our models) and the `rag_chunks`
HNSW/GIN indexes (created via raw `op.execute` in `0e846670f363_s13_rag_search_indexes.
py`, invisible to SQLAlchemy's column-level reflection) - both omitted as false
positives, same as `f6dcf62cdba4`'s own note.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '529d2f1df0af'
down_revision: Union[str, Sequence[str], None] = '6af7c901bab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('question_validation_runs',
    sa.Column('question_validation_run_id', sa.String(), nullable=False),
    sa.Column('question_template_id', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('stage_results', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('cost_cents', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_template_id'], ['question_templates.question_template_id'], ),
    sa.PrimaryKeyConstraint('question_validation_run_id')
    )
    op.add_column('question_templates', sa.Column('authoring_mode', sa.String(), nullable=False, server_default='shape'))
    op.add_column('question_templates', sa.Column('stem', sa.String(), nullable=True))
    op.add_column('question_templates', sa.Column('context_block', sa.String(), nullable=True))
    op.add_column('question_templates', sa.Column('answer_expression', sa.String(), nullable=True))
    op.add_column('question_templates', sa.Column('hint_ladder', sa.JSON(), nullable=True))
    op.add_column('question_templates', sa.Column('canonical_solution', sa.JSON(), nullable=True))
    op.add_column('question_templates', sa.Column('stem_embedding', pgvector.sqlalchemy.Vector(dim=1024), nullable=True))
    op.add_column('question_templates', sa.Column('review_priority', sa.String(), nullable=False, server_default='normal'))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('question_templates', 'review_priority')
    op.drop_column('question_templates', 'stem_embedding')
    op.drop_column('question_templates', 'canonical_solution')
    op.drop_column('question_templates', 'hint_ladder')
    op.drop_column('question_templates', 'answer_expression')
    op.drop_column('question_templates', 'context_block')
    op.drop_column('question_templates', 'stem')
    op.drop_column('question_templates', 'authoring_mode')
    op.drop_table('question_validation_runs')
