"""s12_embedding_dim_1024

Revision ID: 8bcfca8c70f2
Revises: d4f32ead2290
Create Date: 2026-07-17 00:45:05.394800

S12 picks Amazon Titan Text Embeddings V2 (1024-dim) as the real embedding model
(D-035), replacing the 1536 placeholder `EMBEDDING_DIM` that's been in place since S3.
`rag_chunks.embedding` has never been written to (no ingestion pipeline existed until
this session), so this is a plain type-widen/narrow with no data to migrate.

The autogenerated diff also proposed dropping the LangGraph `checkpoint*` tables
(created at runtime by `AsyncPostgresSaver`, not by our models) - intentionally omitted,
same as f6dcf62cdba4 and d4f32ead2290 before it.
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '8bcfca8c70f2'
down_revision: Union[str, Sequence[str], None] = 'd4f32ead2290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('rag_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('rag_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
