"""initial domain schema

Revision ID: 9e6877432c14
Revises: 
Create Date: 2026-07-15 13:33:28.285968

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e6877432c14'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('assessment_sessions',
    sa.Column('assessment_session_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('assessment_session_id')
    )
    op.create_index(op.f('ix_assessment_sessions_student_external_id'), 'assessment_sessions', ['student_external_id'], unique=False)
    op.create_table('blocked_sessions',
    sa.Column('blocked_session_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('week_id', sa.String(), nullable=False),
    sa.Column('blocked_reason', sa.String(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('blocked_session_id')
    )
    op.create_index(op.f('ix_blocked_sessions_student_external_id'), 'blocked_sessions', ['student_external_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('evaluation_result_id', sa.String(), nullable=False),
    sa.Column('suite_name', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('evaluation_result_id')
    )
    op.create_table('rag_documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('branch_external_id', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('supersedes_document_id', sa.String(), nullable=True),
    sa.Column('source_sha256', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_document_id'], ['rag_documents.document_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('topics',
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('curriculum_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grade_band', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('learning_gain',
    sa.Column('learning_gain_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('pre_assessment_session_id', sa.String(), nullable=False),
    sa.Column('post_assessment_session_id', sa.String(), nullable=False),
    sa.Column('pre_raw_score', sa.Float(), nullable=False),
    sa.Column('post_raw_score', sa.Float(), nullable=False),
    sa.Column('raw_gain', sa.Float(), nullable=False),
    sa.Column('weighted_gain', sa.Float(), nullable=False),
    sa.Column('normalized_gain', sa.Float(), nullable=True),
    sa.Column('normalized_gain_status', sa.String(), nullable=True),
    sa.Column('skill_level_gain', sa.JSON(), nullable=False),
    sa.Column('difficulty_transition', sa.JSON(), nullable=False),
    sa.Column('independent_correct_rate', sa.Float(), nullable=False),
    sa.Column('hint_dependency', sa.Float(), nullable=False),
    sa.Column('solution_dependency', sa.Float(), nullable=False),
    sa.Column('unresolved_skills', sa.JSON(), nullable=False),
    sa.Column('response_time_change_ms', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_assessment_session_id'], ['assessment_sessions.assessment_session_id'], ),
    sa.ForeignKeyConstraint(['pre_assessment_session_id'], ['assessment_sessions.assessment_session_id'], ),
    sa.PrimaryKeyConstraint('learning_gain_id')
    )
    op.create_index(op.f('ix_learning_gain_student_external_id'), 'learning_gain', ['student_external_id'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('parent_chunk_id', sa.String(), nullable=True),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('document_title', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('branch_external_id', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_sha256', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.document_id'], ),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['rag_chunks.chunk_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('study_sessions',
    sa.Column('study_session_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('target_skill_ids', sa.JSON(), nullable=False),
    sa.Column('starting_difficulty', sa.Integer(), nullable=False),
    sa.Column('base_problem_count', sa.Integer(), nullable=False),
    sa.Column('maximum_attempts_per_skill', sa.Integer(), nullable=False),
    sa.Column('intervention_policy', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('study_session_id')
    )
    op.create_index(op.f('ix_study_sessions_student_external_id'), 'study_sessions', ['student_external_id'], unique=False)
    op.create_table('mastery',
    sa.Column('mastery_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('raw_accuracy', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('accuracy_by_difficulty', sa.JSON(), nullable=False),
    sa.Column('highest_consistent_difficulty', sa.Integer(), nullable=True),
    sa.Column('estimated_theta', sa.Float(), nullable=True),
    sa.Column('theta_confidence_interval', sa.JSON(), nullable=True),
    sa.Column('mastery_probability', sa.Float(), nullable=True),
    sa.Column('recommended_difficulty', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('mastery_id')
    )
    op.create_index(op.f('ix_mastery_student_external_id'), 'mastery', ['student_external_id'], unique=False)
    op.create_table('question_templates',
    sa.Column('question_template_id', sa.String(), nullable=False),
    sa.Column('curriculum_version', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('grade_band', sa.String(), nullable=False),
    sa.Column('difficulty_label', sa.Integer(), nullable=False),
    sa.Column('difficulty_confidence', sa.Float(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=False),
    sa.Column('generation_constraints', sa.JSON(), nullable=False),
    sa.Column('solution_function', sa.String(), nullable=False),
    sa.Column('correct_option_generator', sa.String(), nullable=False),
    sa.Column('distractor_generators', sa.JSON(), nullable=False),
    sa.Column('common_error_tags', sa.JSON(), nullable=False),
    sa.Column('estimated_time_seconds', sa.Integer(), nullable=False),
    sa.Column('generator_model', sa.String(), nullable=False),
    sa.Column('review_model_versions', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('active_status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('question_template_id')
    )
    op.create_table('semantic_memory',
    sa.Column('semantic_memory_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('fact_type', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('skill_id', sa.String(), nullable=True),
    sa.Column('fact_text', sa.String(), nullable=False),
    sa.Column('structured_value', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_event_ids', sa.JSON(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memory_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('semantic_memory_id')
    )
    op.create_index(op.f('ix_semantic_memory_student_external_id'), 'semantic_memory', ['student_external_id'], unique=False)
    op.create_table('question_variants',
    sa.Column('question_variant_id', sa.String(), nullable=False),
    sa.Column('question_template_id', sa.String(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('rendered_question', sa.String(), nullable=False),
    sa.Column('option_a', sa.String(), nullable=False),
    sa.Column('option_b', sa.String(), nullable=False),
    sa.Column('option_c', sa.String(), nullable=False),
    sa.Column('option_d', sa.String(), nullable=False),
    sa.Column('correct_option', sa.String(), nullable=False),
    sa.Column('parameter_values', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_template_id'], ['question_templates.question_template_id'], ),
    sa.PrimaryKeyConstraint('question_variant_id')
    )
    op.create_table('assessment_attempts',
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('assessment_session_id', sa.String(), nullable=False),
    sa.Column('question_variant_id', sa.String(), nullable=False),
    sa.Column('selected_option', sa.String(), nullable=False),
    sa.Column('correct_option', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.assessment_session_id'], ),
    sa.ForeignKeyConstraint(['question_variant_id'], ['question_variants.question_variant_id'], ),
    sa.PrimaryKeyConstraint('attempt_id'),
    sa.UniqueConstraint('assessment_session_id', 'question_variant_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_assessment_attempts_student_external_id'), 'assessment_attempts', ['student_external_id'], unique=False)
    op.create_table('assessment_items',
    sa.Column('assessment_item_id', sa.String(), nullable=False),
    sa.Column('assessment_session_id', sa.String(), nullable=False),
    sa.Column('question_variant_id', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.assessment_session_id'], ),
    sa.ForeignKeyConstraint(['question_variant_id'], ['question_variants.question_variant_id'], ),
    sa.PrimaryKeyConstraint('assessment_item_id')
    )
    op.create_table('learning_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('skill_id', sa.String(), nullable=True),
    sa.Column('question_variant_id', sa.String(), nullable=True),
    sa.Column('structured_payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_variant_id'], ['question_variants.question_variant_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_learning_events_student_external_id'), 'learning_events', ['student_external_id'], unique=False)
    op.create_table('problem_reports',
    sa.Column('problem_report_id', sa.String(), nullable=False),
    sa.Column('question_template_id', sa.String(), nullable=False),
    sa.Column('question_variant_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_template_id'], ['question_templates.question_template_id'], ),
    sa.ForeignKeyConstraint(['question_variant_id'], ['question_variants.question_variant_id'], ),
    sa.PrimaryKeyConstraint('problem_report_id'),
    sa.UniqueConstraint('question_template_id', 'student_external_id')
    )
    op.create_table('study_attempts',
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('student_external_id', sa.String(), nullable=False),
    sa.Column('study_session_id', sa.String(), nullable=False),
    sa.Column('question_variant_id', sa.String(), nullable=False),
    sa.Column('selected_option', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('video_used', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('outcome_label', sa.String(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_variant_id'], ['question_variants.question_variant_id'], ),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.study_session_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_study_attempts_student_external_id'), 'study_attempts', ['student_external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_attempts_student_external_id'), table_name='study_attempts')
    op.drop_table('study_attempts')
    op.drop_table('problem_reports')
    op.drop_index(op.f('ix_learning_events_student_external_id'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_table('assessment_items')
    op.drop_index(op.f('ix_assessment_attempts_student_external_id'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_table('question_variants')
    op.drop_index(op.f('ix_semantic_memory_student_external_id'), table_name='semantic_memory')
    op.drop_table('semantic_memory')
    op.drop_table('question_templates')
    op.drop_index(op.f('ix_mastery_student_external_id'), table_name='mastery')
    op.drop_table('mastery')
    op.drop_index(op.f('ix_study_sessions_student_external_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_table('skills')
    op.drop_table('rag_chunks')
    op.drop_index(op.f('ix_learning_gain_student_external_id'), table_name='learning_gain')
    op.drop_table('learning_gain')
    op.drop_table('topics')
    op.drop_table('rag_documents')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_blocked_sessions_student_external_id'), table_name='blocked_sessions')
    op.drop_table('blocked_sessions')
    op.drop_index(op.f('ix_assessment_sessions_student_external_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    # ### end Alembic commands ###
