"""d402_chat_turn_cancellations - turn-scoped cancellation requests

Revision ID: a1c7e2b90d44
Revises: ecee04921753
Create Date: 2026-08-18

Additive and reversible: one new table, no changes to existing ones, no data touched. The
downgrade drops it, and dropping it loses nothing - a row is a request to stop a turn that is
running *now*, so the table is empty at rest and anything in it is stale within a minute.

**Why this is a table rather than a signal** is in `ChatTurnCancellation`'s own docstring: the
cancel is a separate HTTP request that may land on a different ECS task than the running turn,
and `LISTEN`/`NOTIFY` is deliberately fire-and-forget here, which is the wrong failure mode when
a dropped message means the lock stays held.

Hand-written, not autogenerated - see `6538a95bc990` and D-332 for why every migration in this
project is read before it is run.
"""

import sqlalchemy as sa
from alembic import op

revision = "a1c7e2b90d44"
down_revision = "ecee04921753"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "chat_turn_cancellations",
        sa.Column("chat_session_id", sa.String(), nullable=False),
        # Bounded to match `AskMessageRequest.client_turn_id`. The server never mints one.
        sa.Column("client_turn_id", sa.String(length=64), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        # Composite PK, so a visitor pressing Stop twice writes one row rather than two, and the
        # observing turn's lookup is a primary-key hit rather than a scan.
        sa.PrimaryKeyConstraint("chat_session_id", "client_turn_id"),
    )


def downgrade() -> None:
    op.drop_table("chat_turn_cancellations")
