"""s11 learning gain session and topic linkage

Revision ID: d4f32ead2290
Revises: f6dcf62cdba4
Create Date: 2026-07-16 22:38:39.458828

Adds `learning_gain.study_session_id`/`.topic_id` (both nullable) so a completed
pre->study->post cycle can be traced back to its study session and topic (SPEC §5.14.3
parent dashboard, S11) - no FK/grouping id did this since the `LearningSession` table
that once linked all three phases was retired in S6. Both nullable, no `server_default`:
existing rows simply have no linkage, and the application always sets both going forward.

The autogenerated diff also proposed dropping the LangGraph `checkpoint*` tables (created
at runtime by `AsyncPostgresSaver`, not by our models) - those drops are intentionally
omitted, same as every prior migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd4f32ead2290'
down_revision: Union[str, Sequence[str], None] = 'f6dcf62cdba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Matches Postgres's own default `<table>_<column>_fkey` naming, same as every other FK
# on this table - needed explicitly here only because `downgrade()` must name the
# constraint it drops.
FK_TOPIC = 'learning_gain_topic_id_fkey'
FK_STUDY_SESSION = 'learning_gain_study_session_id_fkey'


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('learning_gain', sa.Column('study_session_id', sa.String(), nullable=True))
    op.add_column('learning_gain', sa.Column('topic_id', sa.String(), nullable=True))
    op.create_foreign_key(FK_TOPIC, 'learning_gain', 'topics', ['topic_id'], ['topic_id'])
    op.create_foreign_key(
        FK_STUDY_SESSION,
        'learning_gain',
        'study_sessions',
        ['study_session_id'],
        ['study_session_id'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(FK_STUDY_SESSION, 'learning_gain', type_='foreignkey')
    op.drop_constraint(FK_TOPIC, 'learning_gain', type_='foreignkey')
    op.drop_column('learning_gain', 'topic_id')
    op.drop_column('learning_gain', 'study_session_id')
