"""d336_learning_gain_unique_cycle - one gain row per (pre, post), enforced

Revision ID: ecee04921753
Revises: 4cfc45b7c5ff
Create Date: 2026-08-15

**⚠️ THIS MIGRATION DELETES ROWS.** Run explicitly at the user's request (D-336), and the deletion
is bounded to rows that are redundant by construction.

D-336 made `record_learning_gain` return the existing row for a `(pre, post)` pair instead of
inserting a second, which stops *new* duplicates. It cannot stop two truly concurrent finalizes
from both passing the check, and it does not remove the one that already exists. This adds the
constraint that closes both - and a unique constraint cannot be created while a duplicate is
present, so the de-duplication has to come first, in the same transaction.

**What is deleted, exactly:** for each `(pre_assessment_session_id, post_assessment_session_id)`
group with more than one row, every row except the one with the **earliest `computed_at`**
(`learning_gain_id` breaks a tie deterministically). Nothing else, ever.

**Why that loses nothing.** Duplicate rows are recomputations of the same cycle from the same
attempts, so they agree. Measured on staging: the one duplicate had the same post session and
byte-identical numbers - `raw_gain=-1.0`, `normalized_gain=-0.125` - 46 seconds apart. Keeping the
earliest preserves `computed_at` meaning "when this cycle was finalized" rather than "when someone
last retried", which is the same rule the repository guard applies.

**The downgrade drops the constraint and cannot restore deleted rows.** Stated rather than
discovered: this migration is reversible in schema and not in data.

Hand-written, not autogenerated - see `6538a95bc990` and D-332 for why every migration in this
project is read before it is run.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ecee04921753"
down_revision: str | Sequence[str] | None = "4cfc45b7c5ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CONSTRAINT = "uq_learning_gain_pre_post_cycle"


def upgrade() -> None:
    # Keep the earliest row per cycle. `computed_at ASC, learning_gain_id ASC` so a tie is broken
    # the same way on every environment rather than by physical row order.
    op.execute(
        sa.text(
            """
            DELETE FROM learning_gain
            WHERE learning_gain_id IN (
                SELECT learning_gain_id FROM (
                    SELECT learning_gain_id,
                           ROW_NUMBER() OVER (
                               PARTITION BY pre_assessment_session_id,
                                            post_assessment_session_id
                               ORDER BY computed_at, learning_gain_id
                           ) AS rn
                    FROM learning_gain
                ) ranked
                WHERE ranked.rn > 1
            )
            """
        )
    )
    op.create_unique_constraint(
        CONSTRAINT,
        "learning_gain",
        ["pre_assessment_session_id", "post_assessment_session_id"],
    )


def downgrade() -> None:
    # Schema only. The rows deleted above are not recoverable from here.
    op.drop_constraint(CONSTRAINT, "learning_gain", type_="unique")
