"""s10 study retry ladder columns

Revision ID: f6dcf62cdba4
Revises: 4082b669f581
Create Date: 2026-07-16 16:45:13.598901

Adds the S10 retry-ladder / difficulty-routing columns (SPEC §5.11.1-§5.11.7):
- study_items gains `target_skill_id`/`skill_id`/`difficulty`/`is_remediation` so items
  can be served one at a time with dynamic retry/prerequisite remediation instead of a
  fixed 5-question batch.
- study_attempts gains `solution_used` (previously only hint/video were tracked, so
  "correct_after_solution" couldn't be distinguished) and `tutor_review_flagged`
  (§5.11.7 4th unresolved attempt).

`server_default` is supplied on every new NOT NULL column so this applies to a DB that
already holds study rows and still replays cleanly from an empty schema. The application
always sets these columns explicitly; the defaults are migration-safety only. The
autogenerated diff also proposed dropping the LangGraph `checkpoint*` tables (created at
runtime by `AsyncPostgresSaver`, not by our models) - those drops are intentionally
omitted.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f6dcf62cdba4'
down_revision: Union[str, Sequence[str], None] = '4082b669f581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'study_attempts',
        sa.Column('solution_used', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'study_attempts',
        sa.Column(
            'tutor_review_flagged', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        'study_items',
        sa.Column('target_skill_id', sa.String(), nullable=False, server_default=''),
    )
    op.add_column(
        'study_items',
        sa.Column('skill_id', sa.String(), nullable=False, server_default=''),
    )
    op.add_column(
        'study_items',
        sa.Column('difficulty', sa.Integer(), nullable=False, server_default='1'),
    )
    op.add_column(
        'study_items',
        sa.Column('is_remediation', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('study_items', 'is_remediation')
    op.drop_column('study_items', 'difficulty')
    op.drop_column('study_items', 'skill_id')
    op.drop_column('study_items', 'target_skill_id')
    op.drop_column('study_attempts', 'tutor_review_flagged')
    op.drop_column('study_attempts', 'solution_used')
