"""Deterministic figure specifications for questions whose subject is a picture (D-279).

**34 of the 245 taxonomy rows are family C: the figure IS the question.** "What time does
this clock show", "are these triangles congruent", "which point is at (3, -2)" cannot be
authored as text, and every wave so far has deferred them. This is the contract that makes
them authorable.

## Why structured data and not an image

Every other part of an item is verified deterministically - the answer is re-derived from
the equation, the options are checked for uniqueness, the hints are checked for leaks. An
image generated by a model would be the one part of a question nobody could check, sitting
next to a stem whose correctness is proved. So a figure here is **data the gate can read**:
a clock is an hour and a minute, a bar chart is labels and values. The renderer that draws
it is deterministic and lives in the frontend, so the same spec always produces the same
picture, and a diff of a bank file shows what changed about the figure.

That also means no image generation, no blob storage, no new PII surface, and nothing to
delete on a retention schedule - which is a large amount of machinery the alternative would
have needed (SPEC §5.17 exists because images are expensive to hold safely).

## The one property that makes a figure safe

**Every number in the figure must appear somewhere in the item.** A clock showing 3:45 for
a question whose options are 2:15, 4:30, 3:45, 5:00 is coupled to its question; a clock
showing 3:45 next to a stem about 4:15 is a defect no reader would catch quickly and no
other check would see. `figure_numbers_missing_from_item` is that check, and it is the
reason the spec is a set of numbers rather than free-form drawing instructions.

The check reads options and the solution as well as the stem, because for "what time is
this" the numbers are deliberately *not* in the stem - they are the answer.
"""

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class ClockFigure(BaseModel):
    """An analogue clock face. Covers the `Telling Time` rows in grades 1, 2 and 3."""

    kind: Literal["clock"] = "clock"
    hour: int = Field(ge=1, le=12)
    minute: int = Field(ge=0, le=59)

    def numbers(self) -> list[float]:
        return [float(self.hour), float(self.minute)]


class BarChartFigure(BaseModel):
    """A labelled bar chart. Covers the `Graphs & Tables` rows in grades 3, 4 and 5."""

    kind: Literal["bar_chart"] = "bar_chart"
    title: str = ""
    axis_label: str = ""
    categories: list[str] = Field(min_length=2, max_length=6)
    values: list[float] = Field(min_length=2, max_length=6)

    def numbers(self) -> list[float]:
        return list(self.values)


class ShapeFigure(BaseModel):
    """A labelled polygon or circle, drawn from its stated measurements.

    Covers `Triangles and Quadrilaterals`, `Areas and Triangles`, `Circles and Spheres` and
    the angle-relationship rows. The shape is drawn to the proportions the numbers give, so
    a triangle with sides 3, 4, 5 looks like one - the picture cannot disagree with the
    labels because it is computed from them.
    """

    kind: Literal["shape"] = "shape"
    shape: Literal["triangle", "rectangle", "parallelogram", "trapezoid", "circle"]
    side_lengths: list[float] = Field(default_factory=list, max_length=4)
    angle_degrees: list[float] = Field(default_factory=list, max_length=4)
    unit: str = ""

    def numbers(self) -> list[float]:
        return [*self.side_lengths, *self.angle_degrees]


class CoordinateGridFigure(BaseModel):
    """Points and optional segments on a labelled grid.

    Covers `Coordinate planes`, `Coordinate Geometry`, `Transformations`, `Dilation` and
    `Axial and Rotational Symmetry` - all of which are questions about where things are.
    """

    kind: Literal["coordinate_grid"] = "coordinate_grid"
    x_range: tuple[int, int] = (-6, 6)
    y_range: tuple[int, int] = (-6, 6)
    points: list[tuple[float, float]] = Field(min_length=1, max_length=8)
    point_labels: list[str] = Field(default_factory=list, max_length=8)
    # Index pairs into `points`; drawn as straight segments, so a polygon is its own cycle.
    segments: list[tuple[int, int]] = Field(default_factory=list, max_length=12)

    def numbers(self) -> list[float]:
        return [float(v) for point in self.points for v in point]


FigureSpec = Annotated[
    ClockFigure | BarChartFigure | ShapeFigure | CoordinateGridFigure,
    Field(discriminator="kind"),
]

FIGURE_KINDS = ("clock", "bar_chart", "shape", "coordinate_grid")


def figure_numbers_missing_from_item(figure: FigureSpec, *, item_text: str) -> list[float]:
    """Which of the figure's numbers appear nowhere in the item it belongs to.

    The coupling check, and the whole safety argument for letting a figure exist at all. A
    figure is the only part of an item that is not derived from the verified equation, so
    the one thing that must hold is that it is *about the same question*.

    Deliberately a containment check on the rendered text rather than a semantic one: it
    catches the failure that matters (a figure carrying numbers the question never mentions)
    without pretending to understand the geometry. A figure whose numbers all appear can
    still be a bad picture - that is a review finding, and reviewers can see pictures.

    Whole-valued floats are matched as integers too, because an author writes "3" and the
    spec holds 3.0.
    """
    missing: list[float] = []
    for value in figure.numbers():
        candidates = {str(value)}
        if float(value).is_integer():
            candidates.add(str(int(value)))
        if not any(c in item_text for c in candidates):
            missing.append(value)
    return missing


# A "reading": a question whose answer the figure DETERMINES rather than one arithmetic
# derives. "What time does this clock show" has no equation - the clock is the input and
# the answer is what it says. Before this, such items failed the gate for the same reason
# `Museum B` did in the 3-5 wave: the answer is a label and `derive_answer` produces a
# number, so the two can never match.
#
# The resolution is not to reshape the curriculum around the gate. It is that a figure is
# **itself a verifiable source**: `ClockFigure(hour=3, minute=45)` determines "3:45"
# exactly as `Eq(x, 428 * 6)` determines 2568, and a declared option that disagrees is
# wrong by the same standard. This is the Phase-R router's idea - dispatch on what kind of
# answer the item has - applied to the one answer kind that is read rather than computed.
READINGS = (
    "clock_time",
    "chart_max_label",
    "chart_min_label",
    "point_coordinates",
)


def figure_derived_answer(figure: FigureSpec, reading: str) -> str | None:
    """What the figure says, for a question that reads it rather than calculating from it.

    Returns None when the reading does not apply to this figure kind, which the caller must
    treat as a failure rather than a skip - an item declaring a reading its figure cannot
    answer is exactly the mismatch worth catching.
    """
    if reading == "clock_time" and isinstance(figure, ClockFigure):
        return f"{figure.hour}:{figure.minute:02d}"
    if isinstance(figure, BarChartFigure) and len(figure.categories) == len(figure.values):
        if reading == "chart_max_label":
            return figure.categories[figure.values.index(max(figure.values))]
        if reading == "chart_min_label":
            return figure.categories[figure.values.index(min(figure.values))]
    if reading == "point_coordinates" and isinstance(figure, CoordinateGridFigure):
        x, y = figure.points[0]
        return f"({x:g}, {y:g})"
    return None
