"""D-332: `--autogenerate` proposed deleting every live session, and nothing would have stopped it.

LangGraph's `AsyncPostgresSaver` creates its own four tables at application start. They hold every
learning and chat session in the database and they are absent from `Base.metadata`, so
`alembic revision --autogenerate` classifies them as "present in the database, not in the models"
and emits `op.drop_table` for each.

That is not a theoretical reading. The autogenerated draft of `6538a95bc990_d331_learning_sessions`
contained drops for all four tables, against a dev database holding 1,275,766 checkpoint rows. It
was caught by reading the draft before running it. `env.py`'s `include_object` filter exists so
that catching it is a backstop rather than the only defence, and this test exists so the filter is
not quietly removed by someone who does not know what it was for.

**A unit test on the predicate, not a generated migration.** Running autogenerate needs a live
database at a specific revision, which makes it a slow integration test that skips exactly when the
environment is least trustworthy. The predicate is where the decision lives.
"""

from intellichoice_db.migration_filters import include_object

CHECKPOINT_TABLES = (
    "checkpoints",
    "checkpoint_writes",
    "checkpoint_blobs",
    "checkpoint_migrations",
)


def test_reflected_checkpoint_tables_are_excluded() -> None:
    """The case that matters: autogenerate reflecting a table the models do not declare."""
    for table in CHECKPOINT_TABLES:
        assert not include_object(None, table, "table", True, None), (
            f"{table} would be included in an autogenerate diff, which means the next "
            "`make db-revision` emits op.drop_table for it. See this module's docstring."
        )


def test_ordinary_reflected_tables_are_still_compared() -> None:
    """The negative arm. A filter that excluded everything would also hide real drift - a column
    removed from a model would stop generating a migration and the schema would silently diverge."""
    assert include_object(None, "assessment_sessions", "table", True, None)
    assert include_object(None, "learning_sessions", "table", True, None)


def test_a_declared_table_of_the_same_name_is_not_suppressed() -> None:
    """`reflected=False` means the object came from `Base.metadata`. If this project ever declares
    its own model for one of these tables, that is a deliberate act and autogenerate should honour
    it - the filter suppresses "the database has something the models do not", not the name."""
    for table in CHECKPOINT_TABLES:
        assert include_object(None, table, "table", False, None)


def test_indexes_are_not_filtered_by_this_predicate() -> None:
    """Documents a known, accepted gap rather than implying coverage that does not exist.

    Autogenerate also proposes dropping `ix_rag_chunks_embedding_hnsw`,
    `ix_rag_chunks_filter`, `ix_rag_chunks_search_vector` and
    `ix_question_variants_origin_rendered_question`, which earlier migrations create by hand. Those
    are index-level and non-destructive to row data, and filtering them by name would mask a
    genuine index removal - so they remain a read-the-draft responsibility.
    """
    assert include_object(None, "ix_rag_chunks_filter", "index", True, None)
